/* Database schema to keep the structure of entire database. */
CREATE DATABASE vet_clinic;

CREATE TABLE animals (
    id INT,
    name varchar(100),
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg real,
);

ALTER TABLE animals ADD COLUMN species VARCHAR;
create table owners(
	id int generated by default as identity,
	full_name varchar(100),
	age int,
	primary key(id)
);

--create new species table 
create table species(
	id int generated by default as identity,
	name varchar(50),
    primary key(id)
);

-- alter table 
alter table animals drop column species;

alter table animals add species_id int;
alter table animals 
add foreign key(species_id) references species(id)

--add owner column

alter table animals
add owner_id int;

alter table animals add foreign key(owner_id) references owners(id)